Fix translated epub exception
Exception occurred:
  File "/mnt/data/Documents/dev/python/theorie-relative-de-la-monnaie/venv/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 141, in init_templates
    self.theme = Theme(themename, warn=self.warn)
TypeError: __init__() got an unexpected keyword argument 'warn'

Pip installed v1.3.1 is buggy (github is ok...)
Need to replace line 141 by

    self.theme = Theme(themename)